[workspace]
authors = ["Prottasha Dcruze <claradcruze@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "nextflow-workshop"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
nextflow = ">=25.4.7,<26"
fastqc = ">=0.12.1,<0.13"
trimmomatic = ">=0.40,<0.41"
star = "2.6.1d.*"
